***************
*** 144,150 ****
  obj-$(CONFIG_MACH_BRAVO) += board-bravo-smb329.o
  
  obj-$(CONFIG_MACH_HTCLEO) += board-htcleo.o board-htcleo-panel.o
- obj-$(CONFIG_MACH_HTCLEO) += board-htcleo-keypad.o board-htcleo-mmc.o board-htcleo-ts.o ieee754-df.o
  obj-$(CONFIG_MACH_HTCLEO) += board-htcleo-rfkill.o htc_wifi_nvs.o htc_awb_cal.o
  obj-$(CONFIG_MACH_HTCLEO) += board-htcleo-wifi.o board-htcleo-audio.o board-htcleo-ls.o
  obj-$(CONFIG_HTCLEO_BACKLIGHT_LED) += board-htcleo-bl-led.o
--- 144,150 ----
  obj-$(CONFIG_MACH_BRAVO) += board-bravo-smb329.o
  
  obj-$(CONFIG_MACH_HTCLEO) += board-htcleo.o board-htcleo-panel.o
+ obj-$(CONFIG_MACH_HTCLEO) += board-htcleo-keypad.o board-htcleo-mmc.o board-htcleo-ts.o #ieee754-df.o
  obj-$(CONFIG_MACH_HTCLEO) += board-htcleo-rfkill.o htc_wifi_nvs.o htc_awb_cal.o
  obj-$(CONFIG_MACH_HTCLEO) += board-htcleo-wifi.o board-htcleo-audio.o board-htcleo-ls.o
  obj-$(CONFIG_HTCLEO_BACKLIGHT_LED) += board-htcleo-bl-led.o
